INSERT INTO dw.fact_remuneraciones (
    fecha_key,
    empleado_key,
    area_key,
    cargo_key,
    centro_costo_key,
    contrato_key,
    periodo,
    sueldo_base,
    horas_extras,
    sueldo_imponible,
    sueldo_liquido,
    costo_empresa,
    total_haberes,
    total_descuentos,
    total_aportes,
    cantidad_registros
)
VALUES (
    %(fecha_key)s,
    %(empleado_key)s,
    %(area_key)s,
    %(cargo_key)s,
    %(centro_costo_key)s,
    %(contrato_key)s,
    %(periodo)s,
    %(sueldo_base)s,
    %(horas_extras)s,
    %(sueldo_imponible)s,
    %(sueldo_liquido)s,
    %(costo_empresa)s,
    %(total_haberes)s,
    %(total_descuentos)s,
    %(total_aportes)s,
    %(cantidad_registros)s
)
ON CONFLICT (empleado_key, periodo) DO UPDATE SET
    fecha_key = EXCLUDED.fecha_key,
    area_key = EXCLUDED.area_key,
    cargo_key = EXCLUDED.cargo_key,
    centro_costo_key = EXCLUDED.centro_costo_key,
    contrato_key = EXCLUDED.contrato_key,
    sueldo_base = EXCLUDED.sueldo_base,
    horas_extras = EXCLUDED.horas_extras,
    sueldo_imponible = EXCLUDED.sueldo_imponible,
    sueldo_liquido = EXCLUDED.sueldo_liquido,
    costo_empresa = EXCLUDED.costo_empresa,
    total_haberes = EXCLUDED.total_haberes,
    total_descuentos = EXCLUDED.total_descuentos,
    total_aportes = EXCLUDED.total_aportes,
    cantidad_registros = EXCLUDED.cantidad_registros;
