-- ============================================================
-- Industrias ABC - Data Warehouse
-- Plantilla: plantilla_dimension_ddl.sql
-- Objetivo:
--   Servir como base estándar para la creación de nuevas
--   dimensiones del Data Warehouse.
-- Motor:
--   PostgreSQL
-- Esquema:
--   dw
--
-- IMPORTANTE:
--   Esta plantilla debe adaptarse a cada dimensión concreta.
--   No debe copiarse sin revisar grano, business key,
--   tratamiento histórico, relaciones y reglas de calidad.
-- ============================================================


-- ============================================================
-- 1. DEFINICIÓN DE LA DIMENSIÓN
-- ============================================================

CREATE TABLE IF NOT EXISTS dw.dim_nombre_dimension (
    nombre_dimension_key INTEGER GENERATED BY DEFAULT AS IDENTITY,

    -- Business key empresarial o clave homologada estable.
    codigo_dimension VARCHAR(50) NOT NULL,

    -- Atributos descriptivos.
    nombre_dimension VARCHAR(100) NOT NULL,
    descripcion VARCHAR(255),

    -- Ejemplo de FK opcional hacia otra dimensión conformada.
    -- Eliminar si la dimensión no requiere esta relación.
    -- area_key INTEGER NOT NULL,

    CONSTRAINT pk_dim_nombre_dimension
        PRIMARY KEY (nombre_dimension_key),

    CONSTRAINT uq_dim_nombre_dimension_codigo
        UNIQUE (codigo_dimension),

    -- Ejemplo de FK opcional.
    -- CONSTRAINT fk_dim_nombre_dimension_area
    --     FOREIGN KEY (area_key)
    --     REFERENCES dw.dim_area (area_key),

    CONSTRAINT ck_dim_nombre_dimension_key
        CHECK (nombre_dimension_key >= 0),

    CONSTRAINT ck_dim_nombre_dimension_desconocido
        CHECK (
            (
                nombre_dimension_key = 0
                AND codigo_dimension = 'DESCONOCIDO'
            )
            OR
            (
                nombre_dimension_key > 0
                AND codigo_dimension <> 'DESCONOCIDO'
            )
        )
);


-- ============================================================
-- 2. COMENTARIOS DE DOCUMENTACIÓN
-- ============================================================

COMMENT ON TABLE dw.dim_nombre_dimension IS
'Dimensión de ejemplo del Data Warehouse de Industrias ABC. Adaptar el comentario al grano real de la dimensión.';

COMMENT ON COLUMN dw.dim_nombre_dimension.nombre_dimension_key IS
'Clave subrogada de la dimensión. El valor 0 representa miembro desconocido.';

COMMENT ON COLUMN dw.dim_nombre_dimension.codigo_dimension IS
'Business key empresarial o clave homologada estable de la dimensión.';

COMMENT ON COLUMN dw.dim_nombre_dimension.nombre_dimension IS
'Atributo descriptivo principal de la dimensión.';

COMMENT ON COLUMN dw.dim_nombre_dimension.descripcion IS
'Descripción complementaria cuando corresponda.';


-- ============================================================
-- 3. MIEMBRO DESCONOCIDO
-- ============================================================

INSERT INTO dw.dim_nombre_dimension (
    nombre_dimension_key,
    codigo_dimension,
    nombre_dimension,
    descripcion
)
VALUES (
    0,
    'DESCONOCIDO',
    'No informado',
    'Miembro desconocido'
)
ON CONFLICT (nombre_dimension_key) DO NOTHING;


-- ============================================================
-- 4. TRATAMIENTO HISTÓRICO
-- ============================================================

-- SCD TIPO 1
-- ------------------------------------------------------------
-- Utilizar esta estructura base cuando los cambios válidos
-- deban reemplazar el valor anterior sin mantener historial.
--
-- Ejemplos actuales del DW-CORE:
--   dim_area
--   dim_centro_costo
--   dim_cargo
--   dim_turno


-- SCD TIPO 2
-- ------------------------------------------------------------
-- Si la dimensión requiere historial, NO basta con esta
-- plantilla base.
--
-- Evaluar al menos:
--
--   fecha_desde DATE NOT NULL
--   fecha_hasta DATE
--   es_actual BOOLEAN NOT NULL
--
-- y utilizar intervalos:
--
--   [fecha_desde, fecha_hasta)
--
-- Además se debe:
--
--   1. permitir múltiples versiones por business key;
--   2. evitar UNIQUE solamente sobre la business key;
--   3. definir UNIQUE sobre business key + fecha_desde;
--   4. garantizar como máximo una versión actual;
--   5. validar ausencia de solapes históricos;
--   6. documentar qué atributos generan nueva versión;
--   7. definir claramente el tratamiento del miembro
--      desconocido.
--
-- Referencia implementada:
--   dw.dim_empleado


-- ============================================================
-- 5. ÍNDICES
-- ============================================================

-- No crear índices redundantes sobre columnas que ya estén
-- cubiertas por PRIMARY KEY o UNIQUE.
--
-- PostgreSQL no crea automáticamente índices para FOREIGN KEY.
-- Si esta dimensión contiene FK y se utilizarán frecuentemente
-- en joins o validaciones, evaluar índices específicos.
--
-- Ejemplo:
--
-- CREATE INDEX IF NOT EXISTS idx_dim_nombre_dimension_area
-- ON dw.dim_nombre_dimension (area_key);


-- ============================================================
-- 6. REGLAS DE DISEÑO
-- ============================================================

-- Antes de implementar una dimensión, confirmar:
--
--   1. Grano:
--      ¿Qué representa exactamente una fila?
--
--   2. Business key:
--      ¿Cuál es la clave empresarial estable?
--
--   3. Fuente autoritativa:
--      ¿Qué sistema define oficialmente sus atributos?
--
--   4. Homologación:
--      ¿La fuente comparte la business key empresarial o
--      requiere mapping explícito?
--
--   5. Historia:
--      ¿SCD Tipo 1, Tipo 2 u otra estrategia?
--
--   6. Miembro desconocido:
--      Debe utilizar nombre_dimension_key = 0 cuando aplique.
--
--   7. Integridad:
--      Definir PK, FK, UNIQUE y CHECK necesarios.
--
--   8. Índices:
--      Crear sólo los que aporten integridad o rendimiento.
--
--   9. Pruebas:
--      Incorporar o ampliar tests estructurales.
--
--  10. Instalación:
--      Integrar el nuevo script en el instalador correspondiente
--      y validar su ejecución real en PostgreSQL.
--
--  11. ETL:
--      No utilizar IDs locales de fuentes como claves
--      transversales del Data Warehouse.
--
--  12. Revisión:
--      Los casos no resolubles de manera determinística deben
--      enviarse a revisión y no homologarse por aproximación.
-- ============================================================
