-- =============================================================================
-- SISTEMA OPERACIONAL DE CONTABILIDAD — INDUSTRIAS ABC
-- Motor: PostgreSQL
-- Archivo: schema.sql
-- =============================================================================

-- Eliminar tablas en orden de dependencias si existen
DROP TABLE IF EXISTS movimientos_contables CASCADE;
DROP TABLE IF EXISTS cuentas_contables CASCADE;
DROP TABLE IF EXISTS centros_costo CASCADE;
DROP TABLE IF EXISTS areas CASCADE;

-- -----------------------------------------------------------------------------
-- 1. TABLA: areas
-- -----------------------------------------------------------------------------
CREATE TABLE areas (
    area_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo_area VARCHAR(10) NOT NULL,
    nombre_area VARCHAR(100) NOT NULL,
    CONSTRAINT pk_areas PRIMARY KEY (area_id),
    CONSTRAINT uq_areas_codigo_area UNIQUE (codigo_area)
);

-- -----------------------------------------------------------------------------
-- 2. TABLA: centros_costo
-- Relación 1:1 con areas implementada vía FK obligatoria y UNIQUE en area_id
-- -----------------------------------------------------------------------------
CREATE TABLE centros_costo (
    centro_costo_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(10) NOT NULL,
    nombre VARCHAR(100) NOT NULL,
    area_id BIGINT NOT NULL,
    responsable VARCHAR(120) NULL,
    estado VARCHAR(20) NOT NULL,
    CONSTRAINT pk_centros_costo PRIMARY KEY (centro_costo_id),
    CONSTRAINT uq_centros_costo_codigo UNIQUE (codigo),
    CONSTRAINT uq_centros_costo_area_id UNIQUE (area_id),
    CONSTRAINT fk_centros_costo_areas FOREIGN KEY (area_id) 
        REFERENCES areas (area_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_centros_costo_estado CHECK (estado IN ('ACTIVO', 'INACTIVO'))
);

-- -----------------------------------------------------------------------------
-- 3. TABLA: cuentas_contables
-- Jerarquía del plan de cuentas mediante autorreferencia cuenta_padre_id
-- -----------------------------------------------------------------------------
CREATE TABLE cuentas_contables (
    cuenta_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo_cuenta VARCHAR(20) NOT NULL,
    nombre_cuenta VARCHAR(120) NOT NULL,
    tipo_cuenta VARCHAR(30) NOT NULL,
    grupo VARCHAR(50) NOT NULL,
    nivel SMALLINT NOT NULL,
    cuenta_padre_id BIGINT NULL,
    estado VARCHAR(20) NOT NULL,
    CONSTRAINT pk_cuentas_contables PRIMARY KEY (cuenta_id),
    CONSTRAINT uq_cuentas_contables_codigo UNIQUE (codigo_cuenta),
    CONSTRAINT fk_cuentas_contables_padre FOREIGN KEY (cuenta_padre_id) 
        REFERENCES cuentas_contables (cuenta_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_cuentas_contables_nivel CHECK (nivel > 0),
    CONSTRAINT chk_cuentas_contables_estado CHECK (estado IN ('ACTIVA', 'INACTIVA'))
);

-- -----------------------------------------------------------------------------
-- 4. TABLA: movimientos_contables
-- Registro transaccional de movimientos con validaciones de Debe/Haber
-- -----------------------------------------------------------------------------
CREATE TABLE movimientos_contables (
    movimiento_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    fecha DATE NOT NULL,
    cuenta_id BIGINT NOT NULL,
    centro_costo_id BIGINT NOT NULL,
    documento_tipo VARCHAR(30) NOT NULL,
    documento_numero VARCHAR(50) NOT NULL,
    descripcion VARCHAR(250) NOT NULL,
    debe NUMERIC(14,2) NOT NULL,
    haber NUMERIC(14,2) NOT NULL,
    moneda VARCHAR(3) NOT NULL,
    tipo_cambio NUMERIC(12,4) NOT NULL,
    CONSTRAINT pk_movimientos_contables PRIMARY KEY (movimiento_id),
    CONSTRAINT fk_movimientos_cuentas FOREIGN KEY (cuenta_id) 
        REFERENCES cuentas_contables (cuenta_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT fk_movimientos_centros_costo FOREIGN KEY (centro_costo_id) 
        REFERENCES centros_costo (centro_costo_id) ON UPDATE CASCADE ON DELETE RESTRICT,
    CONSTRAINT chk_movimientos_debe_no_negativo CHECK (debe >= 0),
    CONSTRAINT chk_movimientos_haber_no_negativo CHECK (haber >= 0),
    CONSTRAINT chk_movimientos_debe_haber_exclusivo CHECK (
        (debe > 0 AND haber = 0) OR (haber > 0 AND debe = 0)
    ),
    CONSTRAINT chk_movimientos_tipo_cambio CHECK (tipo_cambio > 0)
);

-- Índices operacionales recomendados
CREATE INDEX idx_movimientos_fecha ON movimientos_contables (fecha);
CREATE INDEX idx_movimientos_cuenta ON movimientos_contables (cuenta_id);
CREATE INDEX idx_movimientos_centro_costo ON movimientos_contables (centro_costo_id);