-- ============================================================
-- Industrias ABC - Data Warehouse
-- Script: 100_crear_fact_asistencia.sql
-- Objetivo:
--   Crear la tabla de hechos de asistencia del Data Warehouse.
--
-- Grano:
--   Una fila por empleado empresarial y fecha con registro
--   de asistencia.
--
-- Fuente principal:
--   Sistema Operacional de Asistencia (MySQL).
--
-- Dependencias:
--   dw.dim_fecha
--   dw.dim_empleado
--   dw.dim_area
--   dw.dim_cargo
--   dw.dim_centro_costo
--   dw.dim_turno
--
-- Motor:
--   PostgreSQL
--
-- Esquema:
--   dw
-- ============================================================

CREATE TABLE IF NOT EXISTS dw.fact_asistencia (
    asistencia_fact_key BIGINT GENERATED BY DEFAULT AS IDENTITY,

    -- ========================================================
    -- CLAVES DIMENSIONALES
    -- ========================================================

    fecha_key INTEGER NOT NULL,
    empleado_key INTEGER NOT NULL,
    area_key INTEGER NOT NULL,
    cargo_key INTEGER NOT NULL,
    centro_costo_key INTEGER NOT NULL,
    turno_key INTEGER NOT NULL,

    -- ========================================================
    -- ATRIBUTOS OPERACIONALES
    -- ========================================================

    hora_entrada TIME,
    hora_salida TIME,

    estado_asistencia VARCHAR(30) NOT NULL,

    -- ========================================================
    -- MEDIDAS
    -- ========================================================

    horas_trabajadas NUMERIC(5,2) NOT NULL DEFAULT 0,
    horas_normales NUMERIC(5,2) NOT NULL DEFAULT 0,
    horas_extras NUMERIC(5,2) NOT NULL DEFAULT 0,
    minutos_atraso INTEGER NOT NULL DEFAULT 0,

    dias_trabajados SMALLINT NOT NULL DEFAULT 0,
    dias_ausentes SMALLINT NOT NULL DEFAULT 0,

    cantidad_registros SMALLINT NOT NULL DEFAULT 1,

    -- ========================================================
    -- PRIMARY KEY
    -- ========================================================

    CONSTRAINT pk_fact_asistencia
        PRIMARY KEY (asistencia_fact_key),

    -- ========================================================
    -- UNICIDAD DEL GRANO
    -- ========================================================

    CONSTRAINT uq_fact_asistencia_empleado_fecha
        UNIQUE (empleado_key, fecha_key),

    -- ========================================================
    -- FOREIGN KEYS
    -- ========================================================

    CONSTRAINT fk_fact_asistencia_fecha
        FOREIGN KEY (fecha_key)
        REFERENCES dw.dim_fecha (fecha_key),

    CONSTRAINT fk_fact_asistencia_empleado
        FOREIGN KEY (empleado_key)
        REFERENCES dw.dim_empleado (empleado_key),

    CONSTRAINT fk_fact_asistencia_area
        FOREIGN KEY (area_key)
        REFERENCES dw.dim_area (area_key),

    CONSTRAINT fk_fact_asistencia_cargo
        FOREIGN KEY (cargo_key)
        REFERENCES dw.dim_cargo (cargo_key),

    CONSTRAINT fk_fact_asistencia_centro_costo
        FOREIGN KEY (centro_costo_key)
        REFERENCES dw.dim_centro_costo (centro_costo_key),

    CONSTRAINT fk_fact_asistencia_turno
        FOREIGN KEY (turno_key)
        REFERENCES dw.dim_turno (turno_key),

    -- ========================================================
    -- CHECKS DE DOMINIO Y CALIDAD
    -- ========================================================

    CONSTRAINT ck_fact_asistencia_estado
        CHECK (
            estado_asistencia IN (
                'PRESENTE',
                'ATRASO',
                'AUSENTE'
            )
        ),

    CONSTRAINT ck_fact_asistencia_horas_trabajadas
        CHECK (
            horas_trabajadas >= 0
        ),

    CONSTRAINT ck_fact_asistencia_horas_normales
        CHECK (
            horas_normales >= 0
        ),

    CONSTRAINT ck_fact_asistencia_horas_extras
        CHECK (
            horas_extras >= 0
        ),

    CONSTRAINT ck_fact_asistencia_horas_extras_vs_trabajadas
        CHECK (
            horas_extras <= horas_trabajadas
        ),

    CONSTRAINT ck_fact_asistencia_minutos_atraso
        CHECK (
            minutos_atraso >= 0
        ),

    CONSTRAINT ck_fact_asistencia_dias_trabajados
        CHECK (
            dias_trabajados IN (0, 1)
        ),

    CONSTRAINT ck_fact_asistencia_dias_ausentes
        CHECK (
            dias_ausentes IN (0, 1)
        ),

    CONSTRAINT ck_fact_asistencia_dias_coherentes
        CHECK (
            dias_trabajados + dias_ausentes = 1
        ),

    CONSTRAINT ck_fact_asistencia_cantidad_registros
        CHECK (
            cantidad_registros = 1
        ),

    -- ========================================================
    -- COHERENCIA SEGÚN ESTADO
    -- ========================================================

    CONSTRAINT ck_fact_asistencia_estado_dias
        CHECK (
            (
                estado_asistencia IN ('PRESENTE', 'ATRASO')
                AND dias_trabajados = 1
                AND dias_ausentes = 0
            )
            OR
            (
                estado_asistencia = 'AUSENTE'
                AND dias_trabajados = 0
                AND dias_ausentes = 1
            )
        ),

    CONSTRAINT ck_fact_asistencia_ausencia_coherente
        CHECK (
            estado_asistencia <> 'AUSENTE'
            OR (
                hora_entrada IS NULL
                AND hora_salida IS NULL
                AND horas_trabajadas = 0
                AND horas_normales = 0
                AND horas_extras = 0
                AND minutos_atraso = 0
            )
        )
);

-- ============================================================
-- COMENTARIOS DE DOCUMENTACIÓN
-- ============================================================

COMMENT ON TABLE dw.fact_asistencia IS
'Tabla de hechos de asistencia del Data Warehouse de Industrias ABC. Grano: una fila por empleado empresarial y fecha con registro de asistencia.';

COMMENT ON COLUMN dw.fact_asistencia.asistencia_fact_key IS
'Clave técnica subrogada de la tabla de hechos.';

COMMENT ON COLUMN dw.fact_asistencia.fecha_key IS
'Clave foránea hacia DIM_FECHA correspondiente a la fecha del registro de asistencia.';

COMMENT ON COLUMN dw.fact_asistencia.empleado_key IS
'Clave foránea hacia la versión histórica válida de DIM_EMPLEADO para la fecha del hecho.';

COMMENT ON COLUMN dw.fact_asistencia.area_key IS
'Área organizacional correspondiente a la versión histórica del empleado utilizada en el hecho.';

COMMENT ON COLUMN dw.fact_asistencia.cargo_key IS
'Cargo correspondiente a la versión histórica del empleado utilizada en el hecho.';

COMMENT ON COLUMN dw.fact_asistencia.centro_costo_key IS
'Centro de costo correspondiente a la versión histórica del empleado utilizada en el hecho.';

COMMENT ON COLUMN dw.fact_asistencia.turno_key IS
'Clave del turno operacional asociado al registro de asistencia.';

COMMENT ON COLUMN dw.fact_asistencia.hora_entrada IS
'Hora de entrada informada por el sistema operacional de Asistencia.';

COMMENT ON COLUMN dw.fact_asistencia.hora_salida IS
'Hora de salida informada por el sistema operacional de Asistencia.';

COMMENT ON COLUMN dw.fact_asistencia.estado_asistencia IS
'Estado operacional de asistencia: PRESENTE, ATRASO o AUSENTE.';

COMMENT ON COLUMN dw.fact_asistencia.horas_trabajadas IS
'Cantidad total de horas trabajadas en el registro diario.';

COMMENT ON COLUMN dw.fact_asistencia.horas_normales IS
'Cantidad de horas normales registradas en la jornada.';

COMMENT ON COLUMN dw.fact_asistencia.horas_extras IS
'Cantidad de horas extraordinarias registradas en la jornada.';

COMMENT ON COLUMN dw.fact_asistencia.minutos_atraso IS
'Cantidad de minutos de atraso asociados al registro diario.';

COMMENT ON COLUMN dw.fact_asistencia.dias_trabajados IS
'Indicador aditivo: 1 para PRESENTE o ATRASO; 0 para AUSENTE.';

COMMENT ON COLUMN dw.fact_asistencia.dias_ausentes IS
'Indicador aditivo: 1 para AUSENTE; 0 para PRESENTE o ATRASO.';

COMMENT ON COLUMN dw.fact_asistencia.cantidad_registros IS
'Medida constante igual a 1 para facilitar conteos y agregaciones.';