-- ============================================================
-- Industrias ABC - Data Warehouse
-- Script: 140_crear_fact_remuneraciones.sql
-- Objetivo:
--   Crear FACT_REMUNERACIONES para el dominio analítico RRHH.
--
-- Grano:
--   Una fila por empleado empresarial y período mensual
--   de liquidación.
--
-- Fuente principal:
--   Sistema Operacional de Contratos y Remuneraciones
--   (SQL Server).
--
-- Dependencias:
--   dw.dim_fecha
--   dw.dim_empleado
--   dw.dim_area
--   dw.dim_cargo
--   dw.dim_centro_costo
--   dw.dim_contrato
--
-- Motor:
--   PostgreSQL 16
--
-- Esquema:
--   dw
-- ============================================================

CREATE TABLE IF NOT EXISTS dw.fact_remuneraciones (
    remuneracion_fact_key BIGINT GENERATED BY DEFAULT AS IDENTITY,

    -- ========================================================
    -- CLAVES DIMENSIONALES
    -- ========================================================

    fecha_key INTEGER NOT NULL,
    empleado_key INTEGER NOT NULL,
    area_key INTEGER NOT NULL,
    cargo_key INTEGER NOT NULL,
    centro_costo_key INTEGER NOT NULL,
    contrato_key INTEGER NOT NULL,

    -- ========================================================
    -- ATRIBUTO DEGENERADO / TRAZABILIDAD ANALÍTICA
    -- ========================================================

    periodo CHAR(7) NOT NULL,

    -- ========================================================
    -- MEDIDAS BASE DE LIQUIDACIÓN
    -- ========================================================

    sueldo_base NUMERIC(12,2) NOT NULL DEFAULT 0,
    horas_extras NUMERIC(6,2) NOT NULL DEFAULT 0,
    sueldo_imponible NUMERIC(12,2) NOT NULL DEFAULT 0,
    sueldo_liquido NUMERIC(12,2) NOT NULL DEFAULT 0,
    costo_empresa NUMERIC(12,2) NOT NULL DEFAULT 0,

    -- ========================================================
    -- MEDIDAS DERIVADAS DESDE DETALLE DE LIQUIDACIÓN
    -- ========================================================

    total_haberes NUMERIC(12,2) NOT NULL DEFAULT 0,
    total_descuentos NUMERIC(12,2) NOT NULL DEFAULT 0,
    total_aportes NUMERIC(12,2) NOT NULL DEFAULT 0,

    cantidad_registros SMALLINT NOT NULL DEFAULT 1,

    -- ========================================================
    -- PRIMARY KEY
    -- ========================================================

    CONSTRAINT pk_fact_remuneraciones
        PRIMARY KEY (remuneracion_fact_key),

    -- ========================================================
    -- UNICIDAD DEL GRANO
    -- ========================================================

    CONSTRAINT uq_fact_remuneraciones_empleado_periodo
        UNIQUE (empleado_key, periodo),

    -- ========================================================
    -- FOREIGN KEYS
    -- ========================================================

    CONSTRAINT fk_fact_remuneraciones_fecha
        FOREIGN KEY (fecha_key)
        REFERENCES dw.dim_fecha (fecha_key),

    CONSTRAINT fk_fact_remuneraciones_empleado
        FOREIGN KEY (empleado_key)
        REFERENCES dw.dim_empleado (empleado_key),

    CONSTRAINT fk_fact_remuneraciones_area
        FOREIGN KEY (area_key)
        REFERENCES dw.dim_area (area_key),

    CONSTRAINT fk_fact_remuneraciones_cargo
        FOREIGN KEY (cargo_key)
        REFERENCES dw.dim_cargo (cargo_key),

    CONSTRAINT fk_fact_remuneraciones_centro_costo
        FOREIGN KEY (centro_costo_key)
        REFERENCES dw.dim_centro_costo (centro_costo_key),

    CONSTRAINT fk_fact_remuneraciones_contrato
        FOREIGN KEY (contrato_key)
        REFERENCES dw.dim_contrato (contrato_key),

    -- ========================================================
    -- CHECKS DE PERÍODO
    -- ========================================================

    CONSTRAINT ck_fact_remuneraciones_periodo
        CHECK (
            periodo ~ '^[0-9]{4}-(0[1-9]|1[0-2])$'
        ),

    -- ========================================================
    -- CHECKS DE MEDIDAS
    -- ========================================================

    CONSTRAINT ck_fact_remuneraciones_sueldo_base
        CHECK (sueldo_base >= 0),

    CONSTRAINT ck_fact_remuneraciones_horas_extras
        CHECK (horas_extras >= 0),

    CONSTRAINT ck_fact_remuneraciones_sueldo_imponible
        CHECK (sueldo_imponible >= 0),

    CONSTRAINT ck_fact_remuneraciones_sueldo_liquido
        CHECK (sueldo_liquido >= 0),

    CONSTRAINT ck_fact_remuneraciones_costo_empresa
        CHECK (costo_empresa >= 0),

    CONSTRAINT ck_fact_remuneraciones_total_haberes
        CHECK (total_haberes >= 0),

    CONSTRAINT ck_fact_remuneraciones_total_descuentos
        CHECK (total_descuentos >= 0),

    CONSTRAINT ck_fact_remuneraciones_total_aportes
        CHECK (total_aportes >= 0),

    CONSTRAINT ck_fact_remuneraciones_cantidad_registros
        CHECK (cantidad_registros = 1)
);

-- ============================================================
-- COMENTARIOS DE DOCUMENTACIÓN
-- ============================================================

COMMENT ON TABLE dw.fact_remuneraciones IS
'Tabla de hechos de remuneraciones del Data Warehouse de Industrias ABC. Grano: una fila por empleado empresarial y período mensual de liquidación.';

COMMENT ON COLUMN dw.fact_remuneraciones.remuneracion_fact_key IS
'Clave técnica subrogada de FACT_REMUNERACIONES.';

COMMENT ON COLUMN dw.fact_remuneraciones.fecha_key IS
'Clave hacia DIM_FECHA correspondiente al primer día del período mensual de liquidación.';

COMMENT ON COLUMN dw.fact_remuneraciones.empleado_key IS
'Clave hacia la versión histórica válida de DIM_EMPLEADO correspondiente al período liquidado.';

COMMENT ON COLUMN dw.fact_remuneraciones.area_key IS
'Área organizacional asociada a la versión histórica del empleado utilizada para la liquidación.';

COMMENT ON COLUMN dw.fact_remuneraciones.cargo_key IS
'Cargo asociado a la versión histórica del empleado utilizada para la liquidación.';

COMMENT ON COLUMN dw.fact_remuneraciones.centro_costo_key IS
'Centro de costo asociado a la versión histórica del empleado utilizada para la liquidación.';

COMMENT ON COLUMN dw.fact_remuneraciones.contrato_key IS
'Clave hacia DIM_CONTRATO correspondiente al contrato asociado a la liquidación.';

COMMENT ON COLUMN dw.fact_remuneraciones.periodo IS
'Período mensual de liquidación en formato YYYY-MM.';

COMMENT ON COLUMN dw.fact_remuneraciones.sueldo_base IS
'Sueldo base informado en la liquidación mensual.';

COMMENT ON COLUMN dw.fact_remuneraciones.horas_extras IS
'Cantidad de horas extraordinarias liquidadas en el período.';

COMMENT ON COLUMN dw.fact_remuneraciones.sueldo_imponible IS
'Monto imponible informado por la liquidación fuente.';

COMMENT ON COLUMN dw.fact_remuneraciones.sueldo_liquido IS
'Monto líquido informado por la liquidación fuente.';

COMMENT ON COLUMN dw.fact_remuneraciones.costo_empresa IS
'Costo total empresa informado por la liquidación fuente.';

COMMENT ON COLUMN dw.fact_remuneraciones.total_haberes IS
'Total agregado de conceptos de tipo HABER asociados a la liquidación.';

COMMENT ON COLUMN dw.fact_remuneraciones.total_descuentos IS
'Total agregado de conceptos de tipo DESCUENTO asociados a la liquidación.';

COMMENT ON COLUMN dw.fact_remuneraciones.total_aportes IS
'Total agregado de conceptos de tipo APORTE asociados a la liquidación.';

COMMENT ON COLUMN dw.fact_remuneraciones.cantidad_registros IS
'Medida constante igual a 1 para facilitar conteos y agregaciones.';