-- ============================================================
-- Industrias ABC - Data Warehouse
-- Script: 180_crear_fact_compras.sql
-- Objetivo:
--   Crear la tabla de hechos de compras del Data Warehouse.
--
-- Grano:
--   Una fila por LÍNEA DE DETALLE de una orden de compra
--   (un insumo dentro de una OC). No es a nivel de cabecera.
--
-- Fuente principal:
--   Sistema Operacional de Compras (PostgreSQL).
--
-- Dependencias (dimensiones del CORE + de negocio de Compras):
--   dw.dim_fecha         (role-playing: emisión y requerida)
--   dw.dim_proveedor
--   dw.dim_insumo
--   dw.dim_centro_costo
--   dw.dim_area
--
-- Notas de diseño:
--   - Impuesto y total existen en la CABECERA de la OC y deben
--     PRORRATEARSE al grano de línea en el ETL (Bloque 6):
--       impuesto_linea = impuesto_oc * subtotal_linea / subtotal_oc
--       total_linea    = subtotal_linea + impuesto_linea
--     El DDL define las columnas a nivel de línea; NO calcula el
--     prorrateo (eso es carga ETL).
--   - moneda_origen preserva la moneda real (CLP/USD/EUR); no se
--     suman montos de monedas distintas sin conversión aprobada.
--
-- Motor:   PostgreSQL
-- Esquema: dw
-- ============================================================

CREATE TABLE IF NOT EXISTS dw.fact_compras (
    compra_fact_key BIGINT GENERATED BY DEFAULT AS IDENTITY,

    -- ========================================================
    -- CLAVES DIMENSIONALES
    -- ========================================================

    fecha_emision_key INTEGER NOT NULL,
    fecha_requerida_key INTEGER NOT NULL,
    proveedor_key INTEGER NOT NULL,
    insumo_key INTEGER NOT NULL,
    centro_costo_key INTEGER NOT NULL,
    area_key INTEGER NOT NULL,

    -- ========================================================
    -- ATRIBUTOS / DIMENSIÓN DEGENERADA
    -- ========================================================

    numero_oc VARCHAR(20) NOT NULL,
    codigo_comprador VARCHAR(15),
    estado_oc VARCHAR(20),
    moneda_origen CHAR(3) NOT NULL,

    -- ========================================================
    -- MEDIDAS
    -- ========================================================

    cantidad NUMERIC(12,2) NOT NULL DEFAULT 0,
    precio_unitario NUMERIC(14,2) NOT NULL DEFAULT 0,
    descuento NUMERIC(14,2) NOT NULL DEFAULT 0,
    subtotal NUMERIC(14,2) NOT NULL DEFAULT 0,
    impuesto NUMERIC(14,2) NOT NULL DEFAULT 0,
    total NUMERIC(14,2) NOT NULL DEFAULT 0,
    cantidad_recibida NUMERIC(12,2) NOT NULL DEFAULT 0,
    cantidad_rechazada NUMERIC(12,2) NOT NULL DEFAULT 0,
    cantidad_lineas SMALLINT NOT NULL DEFAULT 1,

    -- ========================================================
    -- PRIMARY KEY
    -- ========================================================

    CONSTRAINT pk_fact_compras
        PRIMARY KEY (compra_fact_key),

    -- ========================================================
    -- UNICIDAD DEL GRANO (una línea por insumo dentro de una OC)
    -- ========================================================

    CONSTRAINT uq_fact_compras_oc_insumo
        UNIQUE (numero_oc, insumo_key),

    -- ========================================================
    -- FOREIGN KEYS
    -- ========================================================

    CONSTRAINT fk_fact_compras_fecha_emision
        FOREIGN KEY (fecha_emision_key)
        REFERENCES dw.dim_fecha (fecha_key),

    CONSTRAINT fk_fact_compras_fecha_requerida
        FOREIGN KEY (fecha_requerida_key)
        REFERENCES dw.dim_fecha (fecha_key),

    CONSTRAINT fk_fact_compras_proveedor
        FOREIGN KEY (proveedor_key)
        REFERENCES dw.dim_proveedor (proveedor_key),

    CONSTRAINT fk_fact_compras_insumo
        FOREIGN KEY (insumo_key)
        REFERENCES dw.dim_insumo (insumo_key),

    CONSTRAINT fk_fact_compras_centro_costo
        FOREIGN KEY (centro_costo_key)
        REFERENCES dw.dim_centro_costo (centro_costo_key),

    CONSTRAINT fk_fact_compras_area
        FOREIGN KEY (area_key)
        REFERENCES dw.dim_area (area_key),

    -- ========================================================
    -- CHECKS DE DOMINIO Y CALIDAD
    -- ========================================================

    CONSTRAINT ck_fact_compras_moneda
        CHECK (moneda_origen IN ('CLP', 'USD', 'EUR')),

    CONSTRAINT ck_fact_compras_estado_oc
        CHECK (
            estado_oc IS NULL
            OR estado_oc IN ('EMITIDA', 'PARCIAL', 'RECIBIDA', 'CERRADA', 'ANULADA')
        ),

    CONSTRAINT ck_fact_compras_cantidad
        CHECK (cantidad >= 0),

    CONSTRAINT ck_fact_compras_precio_unitario
        CHECK (precio_unitario >= 0),

    CONSTRAINT ck_fact_compras_descuento
        CHECK (descuento >= 0),

    CONSTRAINT ck_fact_compras_subtotal
        CHECK (subtotal >= 0),

    CONSTRAINT ck_fact_compras_impuesto
        CHECK (impuesto >= 0),

    CONSTRAINT ck_fact_compras_total
        CHECK (total >= 0),

    CONSTRAINT ck_fact_compras_cantidad_recibida
        CHECK (cantidad_recibida >= 0),

    CONSTRAINT ck_fact_compras_cantidad_rechazada
        CHECK (cantidad_rechazada >= 0),

    CONSTRAINT ck_fact_compras_cantidad_lineas
        CHECK (cantidad_lineas = 1)
);

-- ============================================================
-- COMENTARIOS DE DOCUMENTACIÓN
-- ============================================================

COMMENT ON TABLE dw.fact_compras IS
'Tabla de hechos de compras del Data Warehouse de Industrias ABC. Grano: una fila por línea de detalle de una orden de compra (insumo dentro de una OC). Impuesto y total se prorratean al grano de línea en el ETL.';

COMMENT ON COLUMN dw.fact_compras.compra_fact_key IS
'Clave técnica subrogada de la tabla de hechos.';
COMMENT ON COLUMN dw.fact_compras.fecha_emision_key IS
'FK hacia DIM_FECHA (role-playing): fecha de emisión de la OC.';
COMMENT ON COLUMN dw.fact_compras.fecha_requerida_key IS
'FK hacia DIM_FECHA (role-playing): fecha requerida de la OC. Usar 0 (desconocido) cuando no esté informada.';
COMMENT ON COLUMN dw.fact_compras.proveedor_key IS
'FK hacia DIM_PROVEEDOR resuelta por RUT normalizado.';
COMMENT ON COLUMN dw.fact_compras.insumo_key IS
'FK hacia DIM_INSUMO resuelta por codigo_insumo.';
COMMENT ON COLUMN dw.fact_compras.centro_costo_key IS
'FK hacia DIM_CENTRO_COSTO homologado.';
COMMENT ON COLUMN dw.fact_compras.area_key IS
'FK hacia DIM_AREA asociada al centro de costo.';
COMMENT ON COLUMN dw.fact_compras.numero_oc IS
'Dimensión degenerada: identificador empresarial de la orden de compra.';
COMMENT ON COLUMN dw.fact_compras.codigo_comprador IS
'Atributo local descriptivo del comprador. No se homologa a empleado sin business key común.';
COMMENT ON COLUMN dw.fact_compras.estado_oc IS
'Estado operacional de la OC: EMITIDA, PARCIAL, RECIBIDA, CERRADA o ANULADA.';
COMMENT ON COLUMN dw.fact_compras.moneda_origen IS
'Moneda original de la OC (CLP/USD/EUR). No se suman montos de monedas distintas sin conversión aprobada.';
COMMENT ON COLUMN dw.fact_compras.cantidad IS
'Medida: cantidad solicitada en la línea. Aditiva solo con unidad homogénea.';
COMMENT ON COLUMN dw.fact_compras.precio_unitario IS
'Medida NO aditiva: precio unitario del insumo en la línea.';
COMMENT ON COLUMN dw.fact_compras.descuento IS
'Medida aditiva: descuento de la línea.';
COMMENT ON COLUMN dw.fact_compras.subtotal IS
'Medida aditiva: subtotal de la línea (cantidad*precio - descuento en la fuente).';
COMMENT ON COLUMN dw.fact_compras.impuesto IS
'Medida aditiva: impuesto PRORRATEADO a la línea en el ETL (no repetir impuesto de cabecera).';
COMMENT ON COLUMN dw.fact_compras.total IS
'Medida aditiva: total de línea = subtotal + impuesto prorrateado (calculado en ETL).';
COMMENT ON COLUMN dw.fact_compras.cantidad_recibida IS
'Medida complementaria: cantidad recibida agregada por detalle de OC.';
COMMENT ON COLUMN dw.fact_compras.cantidad_rechazada IS
'Medida complementaria: cantidad rechazada agregada por detalle de OC.';
COMMENT ON COLUMN dw.fact_compras.cantidad_lineas IS
'Medida constante igual a 1 para facilitar conteos de líneas.';
