-- ============================================================
-- Industrias ABC - Data Warehouse
-- Script: 220_crear_fact_produccion.sql
-- Objetivo:
--   Crear la tabla de hechos de Producción a nivel de
--   orden de producción.
-- Motor:
--   PostgreSQL 16
-- Esquema:
--   dw
--
-- Grano:
--   Una fila por orden de producción.
--
-- Dimensiones:
--   - fecha de inicio
--   - fecha de término
--   - producto
--   - centro de costo
--   - área
--
-- Dimensión degenerada:
--   numero_orden.
--
-- Fuente autoritativa:
--   Sistema Operacional de Producción.
--
-- Nota:
--   producto_id y centro_costo_id son identificadores locales
--   de la fuente operacional y no se almacenan como claves
--   transversales del Data Warehouse.
-- ============================================================

CREATE TABLE IF NOT EXISTS dw.fact_produccion (
    produccion_fact_key BIGINT GENERATED BY DEFAULT AS IDENTITY,

    fecha_inicio_key INTEGER NOT NULL,
    fecha_termino_key INTEGER,

    producto_key INTEGER NOT NULL,
    centro_costo_key INTEGER NOT NULL,
    area_key INTEGER NOT NULL,

    numero_orden VARCHAR(50) NOT NULL,

    cantidad_planificada NUMERIC(12,2) NOT NULL,
    cantidad_producida NUMERIC(12,2) NOT NULL,
    cantidad_rechazada NUMERIC(12,2) NOT NULL,

    estado VARCHAR(30) NOT NULL,

    CONSTRAINT pk_fact_produccion
        PRIMARY KEY (produccion_fact_key),

    CONSTRAINT uq_fact_produccion_numero_orden
        UNIQUE (numero_orden),

    CONSTRAINT fk_fact_produccion_fecha_inicio
        FOREIGN KEY (fecha_inicio_key)
        REFERENCES dw.dim_fecha (fecha_key),

    CONSTRAINT fk_fact_produccion_fecha_termino
        FOREIGN KEY (fecha_termino_key)
        REFERENCES dw.dim_fecha (fecha_key),

    CONSTRAINT fk_fact_produccion_producto
        FOREIGN KEY (producto_key)
        REFERENCES dw.dim_producto (producto_key),

    CONSTRAINT fk_fact_produccion_centro_costo
        FOREIGN KEY (centro_costo_key)
        REFERENCES dw.dim_centro_costo (centro_costo_key),

    CONSTRAINT fk_fact_produccion_area
        FOREIGN KEY (area_key)
        REFERENCES dw.dim_area (area_key),

    CONSTRAINT ck_fact_produccion_key
        CHECK (produccion_fact_key >= 0),

    CONSTRAINT ck_fact_produccion_cantidad_planificada
        CHECK (cantidad_planificada >= 0),

    CONSTRAINT ck_fact_produccion_cantidad_producida
        CHECK (cantidad_producida >= 0),

    CONSTRAINT ck_fact_produccion_cantidad_rechazada
        CHECK (cantidad_rechazada >= 0),

    CONSTRAINT ck_fact_produccion_rechazada_no_supera_producida
        CHECK (cantidad_rechazada <= cantidad_producida)
);

COMMENT ON TABLE dw.fact_produccion IS
'Tabla de hechos de Producción. Una fila por orden de producción. No incorpora el detalle de consumo de insumos.';

COMMENT ON COLUMN dw.fact_produccion.produccion_fact_key IS
'Clave técnica del hecho de producción.';

COMMENT ON COLUMN dw.fact_produccion.fecha_inicio_key IS
'Clave de DIM_FECHA correspondiente a la fecha de inicio de la orden de producción.';

COMMENT ON COLUMN dw.fact_produccion.fecha_termino_key IS
'Clave de DIM_FECHA correspondiente a la fecha de término de la orden. Puede ser NULL cuando la fuente no informa fecha de término.';

COMMENT ON COLUMN dw.fact_produccion.producto_key IS
'Clave subrogada de DIM_PRODUCTO correspondiente al producto fabricado.';

COMMENT ON COLUMN dw.fact_produccion.centro_costo_key IS
'Clave subrogada de DIM_CENTRO_COSTO obtenida mediante homologación del centro de costo operacional. No corresponde al centro_costo_id local de Producción.';

COMMENT ON COLUMN dw.fact_produccion.area_key IS
'Clave subrogada de DIM_AREA asociada al centro de costo homologado.';

COMMENT ON COLUMN dw.fact_produccion.numero_orden IS
'Identificador empresarial de la orden de producción. Dimensión degenerada y business key del grano del hecho.';

COMMENT ON COLUMN dw.fact_produccion.cantidad_planificada IS
'Cantidad planificada de producción proveniente de la fuente operacional.';

COMMENT ON COLUMN dw.fact_produccion.cantidad_producida IS
'Cantidad efectivamente producida proveniente de la fuente operacional.';

COMMENT ON COLUMN dw.fact_produccion.cantidad_rechazada IS
'Cantidad rechazada proveniente de la fuente operacional. No puede superar la cantidad producida.';

COMMENT ON COLUMN dw.fact_produccion.estado IS
'Estado operacional de la orden de producción normalizado por el ETL. El dominio concreto se conserva según los valores reales de la fuente.';

COMMENT ON CONSTRAINT uq_fact_produccion_numero_orden
    ON dw.fact_produccion IS
'Protege el grano de una fila por orden de producción.';