-- ============================================================
-- Industrias ABC - Data Warehouse
-- Script: 320_crear_fact_contabilidad.sql
-- Dominio: Contabilidad
--
-- Grano:
--   Una fila por movimiento contable de la fuente operacional.
-- ============================================================

CREATE TABLE IF NOT EXISTS dw.fact_contabilidad (
    contabilidad_fact_key BIGINT GENERATED BY DEFAULT AS IDENTITY,

    -- Trazabilidad de origen. No se utiliza como FK transversal.
    movimiento_id_origen BIGINT NOT NULL,

    -- Claves dimensionales conformadas.
    fecha_key INTEGER NOT NULL,
    cuenta_key INTEGER NOT NULL,
    area_key INTEGER NOT NULL,
    centro_costo_key INTEGER NOT NULL,

    -- Dimensiones degeneradas / atributos del movimiento.
    documento_tipo VARCHAR(30) NOT NULL,
    documento_numero VARCHAR(50) NOT NULL,
    descripcion VARCHAR(250) NOT NULL,
    moneda_origen VARCHAR(3) NOT NULL,
    tipo_cambio NUMERIC(12,4) NOT NULL,

    -- Medidas en moneda de origen.
    debe_origen NUMERIC(18,2) NOT NULL DEFAULT 0,
    haber_origen NUMERIC(18,2) NOT NULL DEFAULT 0,

    -- Medidas analíticas normalizadas a CLP mediante tipo_cambio.
    debe NUMERIC(20,2) NOT NULL DEFAULT 0,
    haber NUMERIC(20,2) NOT NULL DEFAULT 0,
    saldo NUMERIC(20,2) NOT NULL DEFAULT 0,
    cantidad_registros SMALLINT NOT NULL DEFAULT 1,

    CONSTRAINT pk_fact_contabilidad
        PRIMARY KEY (contabilidad_fact_key),

    CONSTRAINT uq_fact_contabilidad_movimiento_origen
        UNIQUE (movimiento_id_origen),

    CONSTRAINT fk_fact_contabilidad_fecha
        FOREIGN KEY (fecha_key)
        REFERENCES dw.dim_fecha (fecha_key),

    CONSTRAINT fk_fact_contabilidad_cuenta
        FOREIGN KEY (cuenta_key)
        REFERENCES dw.dim_cuenta_contable (cuenta_key),

    CONSTRAINT fk_fact_contabilidad_area
        FOREIGN KEY (area_key)
        REFERENCES dw.dim_area (area_key),

    CONSTRAINT fk_fact_contabilidad_centro_costo
        FOREIGN KEY (centro_costo_key)
        REFERENCES dw.dim_centro_costo (centro_costo_key),

    CONSTRAINT ck_fact_contabilidad_tipo_cambio
        CHECK (tipo_cambio > 0),

    CONSTRAINT ck_fact_contabilidad_debe_origen
        CHECK (debe_origen >= 0),

    CONSTRAINT ck_fact_contabilidad_haber_origen
        CHECK (haber_origen >= 0),

    CONSTRAINT ck_fact_contabilidad_debe_haber_origen
        CHECK (
            (debe_origen > 0 AND haber_origen = 0)
            OR
            (haber_origen > 0 AND debe_origen = 0)
        ),

    CONSTRAINT ck_fact_contabilidad_debe
        CHECK (debe >= 0),

    CONSTRAINT ck_fact_contabilidad_haber
        CHECK (haber >= 0),

    CONSTRAINT ck_fact_contabilidad_debe_haber
        CHECK (
            (debe > 0 AND haber = 0)
            OR
            (haber > 0 AND debe = 0)
        ),

    CONSTRAINT ck_fact_contabilidad_saldo
        CHECK (saldo = debe - haber),

    CONSTRAINT ck_fact_contabilidad_cantidad
        CHECK (cantidad_registros = 1)
);

COMMENT ON TABLE dw.fact_contabilidad IS
'Tabla de hechos de Contabilidad. Grano: un movimiento contable. Debe, haber y saldo se almacenan normalizados a CLP; los importes originales y moneda se preservan para trazabilidad.';

COMMENT ON COLUMN dw.fact_contabilidad.movimiento_id_origen IS
'Identificador local del movimiento utilizado solamente para trazabilidad e idempotencia de la carga del mismo sistema origen.';

COMMENT ON COLUMN dw.fact_contabilidad.saldo IS
'Medida firmada normalizada a CLP: debe - haber.';
