-- ============================================================
-- Industrias ABC - Data Warehouse
-- Script: 030_crear_dim_area.sql
-- Objetivo:
--   Crear la dimensión de áreas empresariales homologadas.
-- Motor:
--   PostgreSQL
-- Esquema:
--   dw
-- ============================================================

CREATE TABLE IF NOT EXISTS dw.dim_area (
    area_key INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo_area VARCHAR(20) NOT NULL,
    nombre_area VARCHAR(100) NOT NULL,
    gerencia VARCHAR(100),

    CONSTRAINT pk_dim_area
        PRIMARY KEY (area_key),

    CONSTRAINT uq_dim_area_codigo
        UNIQUE (codigo_area),

    CONSTRAINT ck_dim_area_key
        CHECK (area_key >= 0),

    CONSTRAINT ck_dim_area_desconocido
        CHECK (
            (area_key = 0 AND codigo_area = 'DESCONOCIDO')
            OR
            (area_key > 0 AND codigo_area <> 'DESCONOCIDO')
        )
);

COMMENT ON TABLE dw.dim_area IS
'Dimensión de áreas empresariales homologadas del Data Warehouse de Industrias ABC. Una fila por área.';

COMMENT ON COLUMN dw.dim_area.area_key IS
'Clave subrogada de la dimensión. El valor 0 representa área desconocida.';

COMMENT ON COLUMN dw.dim_area.codigo_area IS
'Business key empresarial del área, por ejemplo A01, A02, A03.';

COMMENT ON COLUMN dw.dim_area.nombre_area IS
'Nombre vigente del área empresarial. Dimensión tratada como SCD Tipo 1.';

COMMENT ON COLUMN dw.dim_area.gerencia IS
'Gerencia asociada al área cuando la fuente autoritativa dispone de esta información.';

INSERT INTO dw.dim_area (
    area_key,
    codigo_area,
    nombre_area,
    gerencia
)
VALUES (
    0,
    'DESCONOCIDO',
    'No informado',
    'No informado'
)
ON CONFLICT (area_key) DO NOTHING;

