-- ============================================================
-- Industrias ABC - Data Warehouse
-- Script: 040_crear_dim_centro_costo.sql
-- Objetivo:
--   Crear la dimensión de centros de costo empresariales
--   homologados.
-- Motor:
--   PostgreSQL
-- Esquema:
--   dw
-- ============================================================

CREATE TABLE IF NOT EXISTS dw.dim_centro_costo (
    centro_costo_key INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo_centro_costo VARCHAR(20) NOT NULL,
    nombre_centro_costo VARCHAR(100) NOT NULL,
    estado VARCHAR(20),

    CONSTRAINT pk_dim_centro_costo
        PRIMARY KEY (centro_costo_key),

    CONSTRAINT uq_dim_centro_costo_codigo
        UNIQUE (codigo_centro_costo),

    CONSTRAINT ck_dim_centro_costo_key
        CHECK (centro_costo_key >= 0),

    CONSTRAINT ck_dim_centro_costo_desconocido
        CHECK (
            (
                centro_costo_key = 0
                AND codigo_centro_costo = 'DESCONOCIDO'
            )
            OR
            (
                centro_costo_key > 0
                AND codigo_centro_costo <> 'DESCONOCIDO'
            )
        )
);

COMMENT ON TABLE dw.dim_centro_costo IS
'Dimensión de centros de costo empresariales homologados del Data Warehouse de Industrias ABC. Una fila por centro de costo.';

COMMENT ON COLUMN dw.dim_centro_costo.centro_costo_key IS
'Clave subrogada de la dimensión. El valor 0 representa centro de costo desconocido.';

COMMENT ON COLUMN dw.dim_centro_costo.codigo_centro_costo IS
'Business key empresarial del centro de costo, por ejemplo CC001, CC002, CC003.';

COMMENT ON COLUMN dw.dim_centro_costo.nombre_centro_costo IS
'Nombre vigente del centro de costo empresarial. Dimensión tratada como SCD Tipo 1.';

COMMENT ON COLUMN dw.dim_centro_costo.estado IS
'Estado vigente del centro de costo cuando la fuente autoritativa dispone de esta información.';

INSERT INTO dw.dim_centro_costo (
    centro_costo_key,
    codigo_centro_costo,
    nombre_centro_costo,
    estado
)
VALUES (
    0,
    'DESCONOCIDO',
    'No informado',
    'DESCONOCIDO'
)
ON CONFLICT (centro_costo_key) DO NOTHING;

