-- ============================================================
-- Industrias ABC - Data Warehouse
-- Script: 050_crear_dim_cargo.sql
-- Objetivo:
--   Crear la dimensión de cargos empresariales homologados.
-- Motor:
--   PostgreSQL
-- Esquema:
--   dw
-- ============================================================

CREATE TABLE IF NOT EXISTS dw.dim_cargo (
    cargo_key INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo_cargo VARCHAR(20) NOT NULL,
    nombre_cargo VARCHAR(100) NOT NULL,
    nivel VARCHAR(50),
    sueldo_base_referencial NUMERIC(14,2),

    CONSTRAINT pk_dim_cargo
        PRIMARY KEY (cargo_key),

    CONSTRAINT uq_dim_cargo_codigo
        UNIQUE (codigo_cargo),

    CONSTRAINT ck_dim_cargo_key
        CHECK (cargo_key >= 0),

    CONSTRAINT ck_dim_cargo_desconocido
        CHECK (
            (
                cargo_key = 0
                AND codigo_cargo = 'DESCONOCIDO'
            )
            OR
            (
                cargo_key > 0
                AND codigo_cargo <> 'DESCONOCIDO'
            )
        ),

    CONSTRAINT ck_dim_cargo_sueldo_referencial
        CHECK (
            sueldo_base_referencial IS NULL
            OR sueldo_base_referencial >= 0
        )
);

COMMENT ON TABLE dw.dim_cargo IS
'Dimensión de cargos empresariales homologados del Data Warehouse de Industrias ABC. Una fila por cargo.';

COMMENT ON COLUMN dw.dim_cargo.cargo_key IS
'Clave subrogada de la dimensión. El valor 0 representa cargo desconocido.';

COMMENT ON COLUMN dw.dim_cargo.codigo_cargo IS
'Business key empresarial del cargo, por ejemplo C01, C02, C03.';

COMMENT ON COLUMN dw.dim_cargo.nombre_cargo IS
'Nombre vigente del cargo empresarial. Dimensión tratada como SCD Tipo 1.';

COMMENT ON COLUMN dw.dim_cargo.nivel IS
'Nivel organizacional o jerárquico del cargo cuando la fuente autoritativa dispone de esta información.';

COMMENT ON COLUMN dw.dim_cargo.sueldo_base_referencial IS
'Valor referencial del cargo. No corresponde al sueldo contractual ni al sueldo base liquidado en FACT_REMUNERACIONES.';

INSERT INTO dw.dim_cargo (
    cargo_key,
    codigo_cargo,
    nombre_cargo,
    nivel,
    sueldo_base_referencial
)
VALUES (
    0,
    'DESCONOCIDO',
    'No informado',
    'No informado',
    NULL
)
ON CONFLICT (cargo_key) DO NOTHING;

