-- ============================================================
-- Industrias ABC - Data Warehouse
-- Script: 060_crear_dim_empleado.sql
-- Objetivo:
--   Crear la dimensión histórica de empleados del
--   Data Warehouse mediante SCD Tipo 2.
-- Motor:
--   PostgreSQL
-- Esquema:
--   dw
-- ============================================================

CREATE TABLE IF NOT EXISTS dw.dim_empleado (
    empleado_key INTEGER GENERATED BY DEFAULT AS IDENTITY,
    rut_normalizado VARCHAR(12) NOT NULL,
    nombres VARCHAR(100) NOT NULL,
    apellido_paterno VARCHAR(100) NOT NULL,
    apellido_materno VARCHAR(100),

    fecha_nacimiento DATE,
    fecha_ingreso DATE,
    fecha_salida DATE,

    area_key INTEGER NOT NULL,
    cargo_key INTEGER NOT NULL,
    centro_costo_key INTEGER NOT NULL,

    estado_laboral VARCHAR(30) NOT NULL,
    sexo VARCHAR(20),
    nacionalidad VARCHAR(50),

    fecha_desde DATE NOT NULL,
    fecha_hasta DATE,
    es_actual BOOLEAN NOT NULL,
    contexto_historico_estimado BOOLEAN NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_dim_empleado
        PRIMARY KEY (empleado_key),

    CONSTRAINT uq_dim_empleado_rut_fecha_desde
        UNIQUE (rut_normalizado, fecha_desde),

    CONSTRAINT fk_dim_empleado_area
        FOREIGN KEY (area_key)
        REFERENCES dw.dim_area (area_key),

    CONSTRAINT fk_dim_empleado_cargo
        FOREIGN KEY (cargo_key)
        REFERENCES dw.dim_cargo (cargo_key),

    CONSTRAINT fk_dim_empleado_centro_costo
        FOREIGN KEY (centro_costo_key)
        REFERENCES dw.dim_centro_costo (centro_costo_key),

    CONSTRAINT ck_dim_empleado_key
        CHECK (empleado_key >= 0),

    CONSTRAINT ck_dim_empleado_desconocido
        CHECK (
            (
                empleado_key = 0
                AND rut_normalizado = 'DESCONOCIDO'
            )
            OR
            (
                empleado_key > 0
                AND rut_normalizado <> 'DESCONOCIDO'
            )
        ),

    CONSTRAINT ck_dim_empleado_vigencia
        CHECK (
            fecha_hasta IS NULL
            OR fecha_hasta > fecha_desde
        ),

    CONSTRAINT ck_dim_empleado_actual
        CHECK (
            (
                es_actual = TRUE
                AND fecha_hasta IS NULL
            )
            OR
            (
                es_actual = FALSE
                AND fecha_hasta IS NOT NULL
            )
        ),

    CONSTRAINT ck_dim_empleado_ingreso_salida
        CHECK (
            fecha_salida IS NULL
            OR fecha_ingreso IS NULL
            OR fecha_salida >= fecha_ingreso
        )
);

COMMENT ON TABLE dw.dim_empleado IS
'Dimensión histórica de empleados del Data Warehouse de Industrias ABC. Implementa SCD Tipo 2 para cambios organizacionales y de estado laboral.';

COMMENT ON COLUMN dw.dim_empleado.empleado_key IS
'Clave subrogada de la versión histórica del empleado. El valor 0 representa empleado desconocido.';

COMMENT ON COLUMN dw.dim_empleado.rut_normalizado IS
'Business key empresarial del empleado. El RUT debe ser normalizado y validado previamente por el ETL.';

COMMENT ON COLUMN dw.dim_empleado.area_key IS
'Clave del área organizacional vigente durante esta versión histórica del empleado.';

COMMENT ON COLUMN dw.dim_empleado.cargo_key IS
'Clave del cargo vigente durante esta versión histórica del empleado.';

COMMENT ON COLUMN dw.dim_empleado.centro_costo_key IS
'Clave del centro de costo vigente o derivado para esta versión histórica del empleado.';

COMMENT ON COLUMN dw.dim_empleado.fecha_desde IS
'Inicio inclusivo de vigencia de la versión SCD2.';

COMMENT ON COLUMN dw.dim_empleado.fecha_hasta IS
'Fin exclusivo de vigencia de la versión SCD2. NULL identifica la versión actual.';

COMMENT ON COLUMN dw.dim_empleado.es_actual IS
'TRUE únicamente para la versión histórica actualmente vigente del empleado.';

COMMENT ON COLUMN dw.dim_empleado.contexto_historico_estimado IS
'TRUE cuando el contexto organizacional histórico fue inferido por ausencia de historia completa en la fuente RRHH.';

INSERT INTO dw.dim_empleado (
    empleado_key,
    rut_normalizado,
    nombres,
    apellido_paterno,
    apellido_materno,
    fecha_nacimiento,
    fecha_ingreso,
    fecha_salida,
    area_key,
    cargo_key,
    centro_costo_key,
    estado_laboral,
    sexo,
    nacionalidad,
    fecha_desde,
    fecha_hasta,
    es_actual,
    contexto_historico_estimado
)
VALUES (
    0,
    'DESCONOCIDO',
    'No informado',
    'No informado',
    'No informado',
    NULL,
    NULL,
    NULL,
    0,
    0,
    0,
    'DESCONOCIDO',
    'No informado',
    'No informado',
    DATE '1900-01-01',
    NULL,
    TRUE,
    FALSE
)
ON CONFLICT (empleado_key) DO NOTHING;
