-- ============================================================
-- Industrias ABC - Data Warehouse
-- Script: 070_crear_dim_turno.sql
-- Objetivo:
--   Crear la dimensión de turnos operativos de Asistencia.
-- Motor:
--   PostgreSQL
-- Esquema:
--   dw
-- ============================================================

CREATE TABLE IF NOT EXISTS dw.dim_turno (
    turno_key INTEGER GENERATED BY DEFAULT AS IDENTITY,
    turno_bk VARCHAR(120) NOT NULL,
    nombre_turno VARCHAR(50) NOT NULL,
    hora_inicio TIME NOT NULL,
    hora_fin TIME NOT NULL,
    horas_jornada NUMERIC(5,2) NOT NULL,

    CONSTRAINT pk_dim_turno
        PRIMARY KEY (turno_key),

    CONSTRAINT uq_dim_turno_bk
        UNIQUE (turno_bk),

    CONSTRAINT ck_dim_turno_key
        CHECK (turno_key >= 0),

    CONSTRAINT ck_dim_turno_desconocido
        CHECK (
            (
                turno_key = 0
                AND turno_bk = 'DESCONOCIDO'
            )
            OR
            (
                turno_key > 0
                AND turno_bk <> 'DESCONOCIDO'
            )
        ),

    CONSTRAINT ck_dim_turno_horas_jornada
        CHECK (
            (turno_key = 0 AND horas_jornada = 0)
            OR
            (turno_key > 0 AND horas_jornada > 0)
        )
);

COMMENT ON TABLE dw.dim_turno IS
'Dimensión de turnos operativos del Data Warehouse de Industrias ABC. Una fila por turno homologado.';

COMMENT ON COLUMN dw.dim_turno.turno_key IS
'Clave subrogada de la dimensión. El valor 0 representa turno desconocido.';

COMMENT ON COLUMN dw.dim_turno.turno_bk IS
'Business key derivada y estable del turno. Se construye a partir del nombre normalizado, hora de inicio y hora de fin.';

COMMENT ON COLUMN dw.dim_turno.nombre_turno IS
'Nombre vigente del turno operativo. Dimensión tratada como SCD Tipo 1.';

COMMENT ON COLUMN dw.dim_turno.hora_inicio IS
'Hora de inicio del turno.';

COMMENT ON COLUMN dw.dim_turno.hora_fin IS
'Hora de término del turno. Puede ser menor que hora_inicio cuando el turno cruza medianoche.';

COMMENT ON COLUMN dw.dim_turno.horas_jornada IS
'Duración referencial de la jornada asociada al turno, expresada en horas.';

INSERT INTO dw.dim_turno (
    turno_key,
    turno_bk,
    nombre_turno,
    hora_inicio,
    hora_fin,
    horas_jornada
)
VALUES (
    0,
    'DESCONOCIDO',
    'No informado',
    TIME '00:00:00',
    TIME '00:00:00',
    0
)
ON CONFLICT (turno_key) DO NOTHING;
