-- ============================================================
-- Industrias ABC - Data Warehouse
-- Script: 120_crear_dim_contrato.sql
-- Objetivo:
--   Crear DIM_CONTRATO para el dominio analítico RRHH.
--
-- Fuente autoritativa:
--   Sistema Operacional de Contratos y Remuneraciones
--   (SQL Server).
--
-- Business key:
--   numero_contrato
--
-- Tratamiento histórico:
--   SCD Tipo 1.
--
-- Motor:
--   PostgreSQL 16
--
-- Esquema:
--   dw
-- ============================================================

CREATE TABLE IF NOT EXISTS dw.dim_contrato (
    contrato_key INTEGER GENERATED BY DEFAULT AS IDENTITY,

    -- ========================================================
    -- BUSINESS KEY
    -- ========================================================

    numero_contrato VARCHAR(20) NOT NULL,

    -- ========================================================
    -- RELACIONES DIMENSIONALES
    -- ========================================================

    empleado_key INTEGER NOT NULL,
    cargo_key INTEGER NOT NULL,

    -- ========================================================
    -- ATRIBUTOS DEL CONTRATO
    -- ========================================================

    tipo_contrato VARCHAR(20) NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_termino DATE,
    jornada VARCHAR(30) NOT NULL,

    sueldo_base_contractual NUMERIC(12,2) NOT NULL,

    -- Texto contractual proveniente de la fuente.
    -- Se conserva aunque cargo_key se resuelva por catálogo.
    cargo_contrato VARCHAR(60) NOT NULL,

    estado_contrato VARCHAR(15) NOT NULL,

    -- ========================================================
    -- PRIMARY KEY
    -- ========================================================

    CONSTRAINT pk_dim_contrato
        PRIMARY KEY (contrato_key),

    -- ========================================================
    -- BUSINESS KEY
    -- ========================================================

    CONSTRAINT uq_dim_contrato_numero
        UNIQUE (numero_contrato),

    -- ========================================================
    -- FOREIGN KEYS
    -- ========================================================

    CONSTRAINT fk_dim_contrato_empleado
        FOREIGN KEY (empleado_key)
        REFERENCES dw.dim_empleado (empleado_key),

    CONSTRAINT fk_dim_contrato_cargo
        FOREIGN KEY (cargo_key)
        REFERENCES dw.dim_cargo (cargo_key),

    -- ========================================================
    -- CHECKS
    -- ========================================================

    CONSTRAINT ck_dim_contrato_key
        CHECK (contrato_key >= 0),

    CONSTRAINT ck_dim_contrato_desconocido
        CHECK (
            (
                contrato_key = 0
                AND numero_contrato = 'DESCONOCIDO'
            )
            OR
            (
                contrato_key > 0
                AND numero_contrato <> 'DESCONOCIDO'
            )
        ),

    CONSTRAINT ck_dim_contrato_tipo
        CHECK (
            tipo_contrato IN (
                'INDEFINIDO',
                'PLAZO_FIJO',
                'TEMPORAL',
                'DESCONOCIDO'
            )
        ),

    CONSTRAINT ck_dim_contrato_estado
        CHECK (
            estado_contrato IN (
                'VIGENTE',
                'TERMINADO',
                'DESCONOCIDO'
            )
        ),

    CONSTRAINT ck_dim_contrato_sueldo_base
        CHECK (
            sueldo_base_contractual >= 0
        ),

    CONSTRAINT ck_dim_contrato_fechas
        CHECK (
            fecha_termino IS NULL
            OR fecha_termino >= fecha_inicio
        ),

    CONSTRAINT ck_dim_contrato_fecha_termino_tipo
        CHECK (
            contrato_key = 0
            OR tipo_contrato = 'INDEFINIDO'
            OR fecha_termino IS NOT NULL
        )
);

-- ============================================================
-- COMENTARIOS
-- ============================================================

COMMENT ON TABLE dw.dim_contrato IS
'Dimensión de contratos laborales del Data Warehouse de Industrias ABC. Business key: numero_contrato. Tratamiento SCD Tipo 1.';

COMMENT ON COLUMN dw.dim_contrato.contrato_key IS
'Clave subrogada del contrato. El valor 0 representa contrato desconocido.';

COMMENT ON COLUMN dw.dim_contrato.numero_contrato IS
'Business key empresarial proveniente del Sistema Operacional de Contratos y Remuneraciones.';

COMMENT ON COLUMN dw.dim_contrato.empleado_key IS
'Clave de DIM_EMPLEADO correspondiente al empleado asociado al contrato. Durante la carga ETL deberá resolverse mediante RUT normalizado y contexto temporal válido.';

COMMENT ON COLUMN dw.dim_contrato.cargo_key IS
'Clave hacia DIM_CARGO. Debe resolverse mediante código empresarial validado; si no existe una equivalencia determinística se utilizará el miembro desconocido 0 hasta su resolución.';

COMMENT ON COLUMN dw.dim_contrato.cargo_contrato IS
'Descripción textual del cargo registrada en el contrato fuente. Se conserva para trazabilidad y validación, pero no reemplaza a cargo_key como relación dimensional.';

COMMENT ON COLUMN dw.dim_contrato.sueldo_base_contractual IS
'Sueldo base pactado en el contrato. No corresponde necesariamente al sueldo base liquidado en un período específico.';

-- ============================================================
-- MIEMBRO DESCONOCIDO
-- ============================================================

INSERT INTO dw.dim_contrato (
    contrato_key,
    numero_contrato,
    empleado_key,
    cargo_key,
    tipo_contrato,
    fecha_inicio,
    fecha_termino,
    jornada,
    sueldo_base_contractual,
    cargo_contrato,
    estado_contrato
)
VALUES (
    0,
    'DESCONOCIDO',
    0,
    0,
    'DESCONOCIDO',
    DATE '1900-01-01',
    NULL,
    'DESCONOCIDO',
    0,
    'No informado',
    'DESCONOCIDO'
)
ON CONFLICT (contrato_key) DO NOTHING;