-- ============================================================
-- Industrias ABC - Data Warehouse
-- Script: 160_crear_dim_proveedor.sql
-- Objetivo:
--   Crear la dimensión de proveedores empresariales del
--   dominio Compras.
-- Motor:
--   PostgreSQL
-- Esquema:
--   dw
--
-- Grano:
--   Una fila por proveedor empresarial.
-- Business key:
--   rut_proveedor_normalizado (RUT normalizado y validado en ETL).
--   No se utiliza razon_social ni IDs locales como clave.
-- Tratamiento histórico:
--   SCD Tipo 1 (los cambios descriptivos válidos reemplazan el valor).
-- Fuente autoritativa:
--   Sistema Operacional de Compras.
-- ============================================================

CREATE TABLE IF NOT EXISTS dw.dim_proveedor (
    proveedor_key INTEGER GENERATED BY DEFAULT AS IDENTITY,
    rut_proveedor_normalizado VARCHAR(12) NOT NULL,
    razon_social VARCHAR(120) NOT NULL,
    nombre_fantasia VARCHAR(120),
    categoria VARCHAR(60),
    region VARCHAR(60),
    comuna VARCHAR(60),
    estado VARCHAR(15),
    codigo_proveedor_ref VARCHAR(15),

    CONSTRAINT pk_dim_proveedor
        PRIMARY KEY (proveedor_key),

    CONSTRAINT uq_dim_proveedor_rut
        UNIQUE (rut_proveedor_normalizado),

    CONSTRAINT ck_dim_proveedor_key
        CHECK (proveedor_key >= 0),

    CONSTRAINT ck_dim_proveedor_desconocido
        CHECK (
            (
                proveedor_key = 0
                AND rut_proveedor_normalizado = 'DESCONOCIDO'
            )
            OR
            (
                proveedor_key > 0
                AND rut_proveedor_normalizado <> 'DESCONOCIDO'
            )
        )
);

COMMENT ON TABLE dw.dim_proveedor IS
'Dimensión de proveedores empresariales del Data Warehouse de Industrias ABC. Una fila por proveedor. Fuente: Compras. SCD Tipo 1.';

COMMENT ON COLUMN dw.dim_proveedor.proveedor_key IS
'Clave subrogada de la dimensión. El valor 0 representa proveedor desconocido.';

COMMENT ON COLUMN dw.dim_proveedor.rut_proveedor_normalizado IS
'Business key empresarial: RUT normalizado y validado (dígito verificador) en el ETL. No se usa razon_social como clave.';

COMMENT ON COLUMN dw.dim_proveedor.razon_social IS
'Razón social vigente del proveedor. Atributo descriptivo (SCD Tipo 1).';

COMMENT ON COLUMN dw.dim_proveedor.nombre_fantasia IS
'Nombre de fantasía o comercial del proveedor.';

COMMENT ON COLUMN dw.dim_proveedor.categoria IS
'Clasificación descriptiva del proveedor.';

COMMENT ON COLUMN dw.dim_proveedor.region IS
'Región del proveedor.';

COMMENT ON COLUMN dw.dim_proveedor.comuna IS
'Comuna del proveedor.';

COMMENT ON COLUMN dw.dim_proveedor.estado IS
'Estado vigente del proveedor según la fuente (ACTIVO / INACTIVO).';

COMMENT ON COLUMN dw.dim_proveedor.codigo_proveedor_ref IS
'Referencia opcional al Universo Master. No reemplaza al RUT como business key.';

INSERT INTO dw.dim_proveedor (
    proveedor_key,
    rut_proveedor_normalizado,
    razon_social,
    nombre_fantasia,
    categoria,
    region,
    comuna,
    estado,
    codigo_proveedor_ref
)
VALUES (
    0,
    'DESCONOCIDO',
    'No informado',
    'No informado',
    'DESCONOCIDO',
    'DESCONOCIDO',
    'DESCONOCIDO',
    'DESCONOCIDO',
    NULL
)
ON CONFLICT (proveedor_key) DO NOTHING;
