-- ============================================================
-- Industrias ABC - Data Warehouse
-- Script: 170_crear_dim_insumo.sql
-- Objetivo:
--   Crear la dimensión de insumos empresariales homologados
--   del dominio Compras.
-- Motor:
--   PostgreSQL
-- Esquema:
--   dw
--
-- Grano:
--   Una fila por insumo empresarial homologado.
-- Business key:
--   codigo_insumo.
-- Tratamiento histórico:
--   SCD Tipo 1. IMPORTANTE: un cambio de unidad_medida para la
--   misma business key NO se aplica como SCD1 silencioso; debe
--   pasar a REVIEW en el ETL (Bloque 6), porque altera el
--   significado histórico de las cantidades. El DDL no lo fuerza:
--   solo lo documenta.
-- Categoría:
--   Desnormalizada dentro de la dimensión (codigo_categoria y
--   nombre_categoria). No se crea DIM_CATEGORIA_INSUMO.
-- Fuente autoritativa:
--   Sistema Operacional de Compras.
-- ============================================================

CREATE TABLE IF NOT EXISTS dw.dim_insumo (
    insumo_key INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo_insumo VARCHAR(20) NOT NULL,
    nombre_insumo VARCHAR(120) NOT NULL,
    codigo_categoria VARCHAR(15),
    nombre_categoria VARCHAR(80),
    unidad_medida VARCHAR(30),
    stock_minimo NUMERIC(12,2),
    estado VARCHAR(15),

    CONSTRAINT pk_dim_insumo
        PRIMARY KEY (insumo_key),

    CONSTRAINT uq_dim_insumo_codigo
        UNIQUE (codigo_insumo),

    CONSTRAINT ck_dim_insumo_key
        CHECK (insumo_key >= 0),

    CONSTRAINT ck_dim_insumo_stock_minimo
        CHECK (stock_minimo IS NULL OR stock_minimo >= 0),

    CONSTRAINT ck_dim_insumo_desconocido
        CHECK (
            (
                insumo_key = 0
                AND codigo_insumo = 'DESCONOCIDO'
            )
            OR
            (
                insumo_key > 0
                AND codigo_insumo <> 'DESCONOCIDO'
            )
        )
);

COMMENT ON TABLE dw.dim_insumo IS
'Dimensión de insumos empresariales homologados del Data Warehouse de Industrias ABC. Una fila por insumo. Fuente: Compras. SCD Tipo 1; cambio de unidad_medida se deriva a REVIEW en el ETL.';

COMMENT ON COLUMN dw.dim_insumo.insumo_key IS
'Clave subrogada de la dimensión. El valor 0 representa insumo desconocido.';

COMMENT ON COLUMN dw.dim_insumo.codigo_insumo IS
'Business key empresarial del insumo (catálogo de Compras).';

COMMENT ON COLUMN dw.dim_insumo.nombre_insumo IS
'Nombre descriptivo vigente del insumo (SCD Tipo 1).';

COMMENT ON COLUMN dw.dim_insumo.codigo_categoria IS
'Código de categoría aplanado dentro de la dimensión (sin DIM_CATEGORIA_INSUMO).';

COMMENT ON COLUMN dw.dim_insumo.nombre_categoria IS
'Nombre de categoría aplanado dentro de la dimensión.';

COMMENT ON COLUMN dw.dim_insumo.unidad_medida IS
'Unidad semántica de las cantidades. Un cambio de este valor pasa a REVIEW en el ETL, no se aplica como SCD1 silencioso.';

COMMENT ON COLUMN dw.dim_insumo.stock_minimo IS
'Stock mínimo vigente de referencia.';

COMMENT ON COLUMN dw.dim_insumo.estado IS
'Estado vigente del insumo según la fuente (ACTIVO / INACTIVO).';

INSERT INTO dw.dim_insumo (
    insumo_key,
    codigo_insumo,
    nombre_insumo,
    codigo_categoria,
    nombre_categoria,
    unidad_medida,
    stock_minimo,
    estado
)
VALUES (
    0,
    'DESCONOCIDO',
    'No informado',
    'DESCONOCIDO',
    'No informado',
    'DESCONOCIDO',
    NULL,
    'DESCONOCIDO'
)
ON CONFLICT (insumo_key) DO NOTHING;
