-- ============================================================
-- Industrias ABC - Data Warehouse
-- Script: 200_crear_dim_producto.sql
-- Objetivo:
--   Crear la dimensión de productos fabricados por
--   Industrias ABC en el dominio Producción.
-- Motor:
--   PostgreSQL 16
-- Esquema:
--   dw
--
-- Grano:
--   Una fila por producto empresarial.
--
-- Business key:
--   codigo_producto.
--
-- Tratamiento histórico:
--   SCD Tipo 1.
--   Los cambios válidos de nombre o categoría reemplazan
--   el valor anterior.
--
-- Regla especial:
--   Un cambio estructural de unidad_medida no debe tratarse
--   como una actualización silenciosa. Ese caso debe pasar
--   a REVIEW durante la carga ETL.
--
-- Fuente autoritativa:
--   Sistema Operacional de Producción.
-- ============================================================

CREATE TABLE IF NOT EXISTS dw.dim_producto (
    producto_key INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo_producto VARCHAR(50) NOT NULL,
    nombre_producto VARCHAR(150) NOT NULL,
    categoria VARCHAR(100) NOT NULL,
    unidad_medida VARCHAR(30) NOT NULL,

    CONSTRAINT pk_dim_producto
        PRIMARY KEY (producto_key),

    CONSTRAINT uq_dim_producto_codigo
        UNIQUE (codigo_producto),

    CONSTRAINT ck_dim_producto_key
        CHECK (producto_key >= 0),

    CONSTRAINT ck_dim_producto_desconocido
        CHECK (
            (
                producto_key = 0
                AND codigo_producto = 'DESCONOCIDO'
            )
            OR
            (
                producto_key > 0
                AND codigo_producto <> 'DESCONOCIDO'
            )
        )
);

COMMENT ON TABLE dw.dim_producto IS
'Dimensión de productos fabricados de Industrias ABC. Una fila por producto empresarial. Fuente autoritativa: Sistema Operacional de Producción. SCD Tipo 1.';

COMMENT ON COLUMN dw.dim_producto.producto_key IS
'Clave subrogada de la dimensión. El valor 0 representa producto desconocido.';

COMMENT ON COLUMN dw.dim_producto.codigo_producto IS
'Business key empresarial del producto proveniente del catálogo operacional de Producción.';

COMMENT ON COLUMN dw.dim_producto.nombre_producto IS
'Nombre vigente del producto. Su actualización corresponde a SCD Tipo 1.';

COMMENT ON COLUMN dw.dim_producto.categoria IS
'Categoría vigente del producto. Su actualización corresponde a SCD Tipo 1.';

COMMENT ON COLUMN dw.dim_producto.unidad_medida IS
'Unidad de medida vigente del producto. Un cambio de unidad debe derivarse a REVIEW durante la carga ETL y no aplicarse silenciosamente como SCD Tipo 1.';

INSERT INTO dw.dim_producto (
    producto_key,
    codigo_producto,
    nombre_producto,
    categoria,
    unidad_medida
)
VALUES (
    0,
    'DESCONOCIDO',
    'No informado',
    'DESCONOCIDO',
    'DESCONOCIDO'
)
ON CONFLICT (producto_key) DO NOTHING;