-- ============================================================
-- Industrias ABC - Data Warehouse
-- Script: 300_crear_dim_cuenta_contable.sql
-- Dominio: Contabilidad
-- ============================================================

CREATE TABLE IF NOT EXISTS dw.dim_cuenta_contable (
    cuenta_key INTEGER GENERATED BY DEFAULT AS IDENTITY,
    codigo_cuenta VARCHAR(20) NOT NULL,
    nombre_cuenta VARCHAR(120) NOT NULL,
    tipo_cuenta VARCHAR(30) NOT NULL,
    grupo VARCHAR(50) NOT NULL,
    nivel SMALLINT NOT NULL,
    codigo_cuenta_padre VARCHAR(20),
    estado VARCHAR(20) NOT NULL,

    CONSTRAINT pk_dim_cuenta_contable
        PRIMARY KEY (cuenta_key),

    CONSTRAINT uq_dim_cuenta_contable_codigo
        UNIQUE (codigo_cuenta),

    CONSTRAINT ck_dim_cuenta_contable_key
        CHECK (cuenta_key >= 0),

    CONSTRAINT ck_dim_cuenta_contable_nivel
        CHECK (
            (cuenta_key = 0 AND nivel = 0)
            OR
            (cuenta_key > 0 AND nivel > 0)
        ),

    CONSTRAINT ck_dim_cuenta_contable_estado
        CHECK (estado IN ('ACTIVA', 'INACTIVA', 'DESCONOCIDO')),

    CONSTRAINT ck_dim_cuenta_contable_desconocido
        CHECK (
            (
                cuenta_key = 0
                AND codigo_cuenta = 'DESCONOCIDO'
            )
            OR
            (
                cuenta_key > 0
                AND codigo_cuenta <> 'DESCONOCIDO'
            )
        )
);

COMMENT ON TABLE dw.dim_cuenta_contable IS
'Dimensión del plan de cuentas de Contabilidad. Business key: codigo_cuenta. Tratamiento SCD Tipo 1.';

COMMENT ON COLUMN dw.dim_cuenta_contable.cuenta_key IS
'Clave subrogada. El valor 0 representa una cuenta no resuelta.';

COMMENT ON COLUMN dw.dim_cuenta_contable.codigo_cuenta IS
'Business key del plan de cuentas contable.';

COMMENT ON COLUMN dw.dim_cuenta_contable.codigo_cuenta_padre IS
'Código de la cuenta superior en la jerarquía operacional; se conserva como atributo dimensional y no como ID local.';

INSERT INTO dw.dim_cuenta_contable (
    cuenta_key,
    codigo_cuenta,
    nombre_cuenta,
    tipo_cuenta,
    grupo,
    nivel,
    codigo_cuenta_padre,
    estado
)
VALUES (
    0,
    'DESCONOCIDO',
    'No informado',
    'DESCONOCIDO',
    'DESCONOCIDO',
    0,
    NULL,
    'DESCONOCIDO'
)
ON CONFLICT (cuenta_key) DO NOTHING;
