INSERT INTO dw.fact_compras (
    fecha_emision_key,
    fecha_requerida_key,
    proveedor_key,
    insumo_key,
    centro_costo_key,
    area_key,
    numero_oc,
    codigo_comprador,
    estado_oc,
    moneda_origen,
    cantidad,
    precio_unitario,
    descuento,
    subtotal,
    impuesto,
    total,
    cantidad_recibida,
    cantidad_rechazada,
    cantidad_lineas
)
VALUES (
    %(fecha_emision_key)s,
    %(fecha_requerida_key)s,
    %(proveedor_key)s,
    %(insumo_key)s,
    %(centro_costo_key)s,
    %(area_key)s,
    %(numero_oc)s,
    %(codigo_comprador)s,
    %(estado_oc)s,
    %(moneda_origen)s,
    %(cantidad)s,
    %(precio_unitario)s,
    %(descuento)s,
    %(subtotal)s,
    %(impuesto)s,
    %(total)s,
    %(cantidad_recibida)s,
    %(cantidad_rechazada)s,
    1
)
ON CONFLICT (numero_oc, insumo_key)
DO UPDATE SET
    fecha_emision_key = EXCLUDED.fecha_emision_key,
    fecha_requerida_key = EXCLUDED.fecha_requerida_key,
    proveedor_key = EXCLUDED.proveedor_key,
    centro_costo_key = EXCLUDED.centro_costo_key,
    area_key = EXCLUDED.area_key,
    codigo_comprador = EXCLUDED.codigo_comprador,
    estado_oc = EXCLUDED.estado_oc,
    moneda_origen = EXCLUDED.moneda_origen,
    cantidad = EXCLUDED.cantidad,
    precio_unitario = EXCLUDED.precio_unitario,
    descuento = EXCLUDED.descuento,
    subtotal = EXCLUDED.subtotal,
    impuesto = EXCLUDED.impuesto,
    total = EXCLUDED.total,
    cantidad_recibida = EXCLUDED.cantidad_recibida,
    cantidad_rechazada = EXCLUDED.cantidad_rechazada,
    cantidad_lineas = 1;
